#@data/values
---

image:
  repository: ""
  tag: latest
  pullPolicy: Always

nginx:
  image:
    repository: "nginx"
    tag: latest
    pullPolicy: Always

imagePullSecrets:
- name: image-registry-credentials

service:
  type: ClusterIP
  port: 80

uaa:
  tls:
    certs_secret_name:

eirini:
  tls:
    certs_secret_name:

resources: {}
