# permissions to do edit kpackbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpackbuild-editor-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - kpackbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - kpackbuilds/status
  verbs:
  - get
  - patch
  - update
