# permissions to do viewer kpackbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpackbuild-viewer-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - kpackbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - kpackbuilds/status
  verbs:
  - get
