
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - build.pivotal.io.build.pivotal.io
  resources:
  - buildren
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.pivotal.io.build.pivotal.io
  resources:
  - buildren/status
  verbs:
  - get
  - patch
  - update
