#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-api-server
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: capi-api-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: capi-api-server
    spec:
      imagePullSecrets:
        - name: image-registry-credentials
      initContainers:
        - name: pre-start
          image: #@ "{}-{}".format(data.values.image.repository, data.values.image.tag)
          imagePullPolicy: #@ data.values.image.pullPolicy
          command:
          - /cloud_controller_ng/pre-start.sh
          volumeMounts:
          - name: cloud-controller-ng-yaml
            mountPath: /config
      containers:
        - name: capi-api-server
          image:  #@ "{}-{}".format(data.values.image.repository, data.values.image.tag)
          imagePullPolicy: #@ data.values.image.pullPolicy
          volumeMounts:
          - name: server-sock
            mountPath: /data/cloud_controller_ng
          - name: cloud-controller-ng-yaml
            mountPath: /config
          #@ if/end data.values.uaa.tls.certs_secret_name:
          - name: uaa-certs
            mountPath: /config/uaa/certs
          #@ if/end data.values.eirini.tls.certs_secret_name:
          - name: eirini-certs
            mountPath: /config/eirini/certs
        - name: nginx
          image: #@ "{}-{}".format(data.values.nginx.image.repository, data.values.nginx.image.tag)
          imagePullPolicy: #@ data.values.nginx.image.pullPolicy
          ports:
          - containerPort: 80
          volumeMounts:
          - name: nginx
            mountPath: /etc/nginx
            readOnly: true
          - name: server-sock
            mountPath: /data/cloud_controller_ng
          - name: nginx-logs
            mountPath: /cloud_controller_ng
      volumes:
      - name: server-sock
        emptyDir: {}
      - name: cloud-controller-ng-yaml
        configMap:
          name: cloud-controller-ng-yaml
      - name: nginx
        configMap:
          name: nginx
      - name: nginx-logs
        emptyDir: {}
      #! TODO: use a single CA for everything plz
      #@ if/end data.values.uaa.tls.certs_secret_name:
      - name: uaa-certs
        secret:
          secretName: {{ .Values.uaa_tls_certs_secret_name }}
      #@ if/end data.values.eirini.tls.certs_secret_name:
      - name: eirini-certs
        secret:
          secretName: {{ .Values.eirini_tls_certs_secret_name }}

