apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment-updater
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "capi-k8s-release.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-deployment-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-deployment-updater
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name  }}-deployment-updater
          workingDir: "/cloud_controller_ng"
          command: ["/usr/local/bin/bundle"]
          args: ["exec", "rake", "deployment_updater:start"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: cloud-controller-ng-yaml
            mountPath: /config
      volumes:
      - name: cloud-controller-ng-yaml
        configMap:
          name: cloud-controller-ng-yaml
