#@ load("@ytt:data","data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-controller-ng-secrets-yaml
  namespace: #@ data.values.system_namespace
  annotations:
    kapp.k14s.io/versioned: ""
data:
  #! TODO: maybe extract this into a lib?
  secrets.yml: |
    db:
      database:
        #! TODO: template this?
        password: /etc/capi/ccdb/password
