#@ load("@ytt:data","data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-controller-ng-secrets-yaml
  namespace: #@ data.values.system_namespace
  annotations:
    kapp.k14s.io/versioned: ""
data:
  #! TODO: maybe extract this into a lib?
  secrets.yml: |
    #! TODO: template these filepaths?
    cloud_controller_username_lookup_client_secret: /etc/cf-api/username-lookup-client-secret/password
    db:
      database:
        password: /etc/cf-api/ccdb/password
    resource_pool:
      fog_connection:
        aws_secret_access_key: /etc/cf-api/blobstore/secret-access-key/password
    packages:
      fog_connection:
        aws_secret_access_key: /etc/cf-api/blobstore/secret-access-key/password
    droplets:
      fog_connection:
        aws_secret_access_key: /etc/cf-api/blobstore/secret-access-key/password
    buildpacks:
      fog_connection:
        aws_secret_access_key: /etc/cf-api/blobstore/secret-access-key/password
