apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "capi-k8s-release.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-worker
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name  }}-worker
          workingDir: "/cloud_controller_ng"
          command: ["/usr/local/bin/bundle"]
          args: ["exec", "rake", "jobs:generic"]
          image: "{{ .Values.image.capi.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: cloud-controller-ng-yaml
            mountPath: /config
      volumes:
      - name: cloud-controller-ng-yaml
        configMap:
          name: cloud-controller-ng-yaml

