# permissions for end users to edit buildren.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: build-editor-role
rules:
- apiGroups:
  - build.pivotal.io.build.pivotal.io
  resources:
  - buildren
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.pivotal.io.build.pivotal.io
  resources:
  - buildren/status
  verbs:
  - get
