#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials-cf-metadata
  namespace: #@ data.values.namespace
type: kubernetes.io/dockerconfigjson
data:
  #@ data.values.registry.hostname
  #@ data.values.registry.password
  #@ data.values.registry.username

  #@ docker_auth = base64.encode("{}:{}".format(data.values.registry.username, data.values.registry.password))
  #@ docker_creds = {"username": data.values.registry.username, "password": data.values.registry.password, "auth": docker_auth}
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {data.values.registry.hostname: docker_creds}}))

---

apiVersion: v1
kind: Secret
metadata:
  name: cf-credentials-cf-metadata
  namespace: #@ data.values.namespace
  labels:
    app: backup-restore
data:
  username: #@ base64.encode(data.values.cf.admin_username)
  password: #@ base64.encode(data.values.cf.admin_password)